/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class SBAlert;

__attribute__((visibility("hidden")))
@interface SBAlertView : XXUnknownSuperclass {
	SBAlert* _alert;
	unsigned _shouldAnimateIn : 1;
}
@property(retain) SBAlert* alert;
@property(assign) BOOL shouldAnimateIn;
- (id)initWithFrame:(CGRect)frame;
- (void)alertDisplayBecameVisible;
- (void)alertDisplayWillBecomeVisible;
- (void)alertWindowViewControllerResizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame2;
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
- (void)dismiss;
- (BOOL)isAnimatingOut;
- (BOOL)isReadyToBeRemovedFromView;
- (BOOL)isSupportedInterfaceOrientation:(int)orientation;
- (void)layoutForInterfaceOrientation:(int)interfaceOrientation;
- (BOOL)shouldAddClippingViewDuringRotation;
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
@end

