/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"

@class UIViewController;

__attribute__((visibility("hidden")))
@interface SBAlertAdapter : SBAlert {
	UIViewController* _effectiveViewController;
}
@property(retain) id display;
@property(readonly, retain) UIViewController* effectiveViewController;
- (id)initWithViewController:(id)viewController;
- (id)alertDisplayViewWithSize:(CGSize)size;
- (void)alertWindow:(id)window resizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame3;
- (void)dealloc;
- (id)description;
- (void)setView:(id)view;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
- (unsigned)supportedInterfaceOrientations;
@end

