/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAwayListItem.h"

@class NSString, BBObserver, NSMutableArray, NSDate, BBBulletin, UIImage;

__attribute__((visibility("hidden")))
@interface SBAwayBulletinListItem : SBAwayListItem {
	NSMutableArray* _bulletins;
	int _personID;
	NSString* _contactInfo;
	BBObserver* _observer;
	NSDate* _sortDate;
	NSDate* _displayDate;
	NSString* _message;
	UIImage* _listItemImage;
	BBBulletin* _activeBulletin;
}
@property(retain) BBBulletin* activeBulletin;
@property(readonly, retain) NSMutableArray* bulletins;
@property(readonly, retain) NSString* message;
@property(readonly, retain) BBObserver* observer;
@property(readonly, retain) NSDate* sortDate;
- (id)initWithBulletin:(id)bulletin andObserver:(id)observer;
- (BOOL)_suppressesMessageForPrivacy;
- (void)_update;
- (void)_updateActiveBulletin;
- (void)_updateButtonLabels;
- (void)_updateDisplayDate;
- (void)_updateImage;
- (void)_updateMessage;
- (void)_updateSortDate;
- (void)addBulletin:(id)bulletin;
- (id)attachmentImageForKey:(id)key;
- (id)attachmentText;
- (id)bulletinWithID:(id)anId;
- (void)buttonPressed;
- (BOOL)canBeClearedByNotificationCenter;
- (BOOL)canCoalesceWithBulletin:(id)bulletin;
- (BOOL)canSnooze;
- (BOOL)containsBulletinWithID:(id)anId;
- (id)date;
- (void)dealloc;
- (id)description;
- (BOOL)hasEventDate;
- (BOOL)hasSamePersonAsBulletin:(id)bulletin;
- (id)iconImage;
- (BOOL)inertWhenLocked;
- (BOOL)isCritical;
- (BOOL)isVIP;
- (unsigned)maxMessageLines;
- (void)modifyBulletin:(id)bulletin;
- (BOOL)overridesQuietMode;
- (id)publishDate;
- (void)removeAllBulletins;
- (void)removeBulletin:(id)bulletin;
- (int)snoozeButtonindex;
- (id)sortedBulletins;
- (id)subtitle;
- (id)title;
- (BOOL)wantsHighlightOnInsert;
@end

