/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBBBulletinInfo.h"
#import "SpringBoard-Structs.h"

@class SBWidgetViewControllerHost, NSString;

__attribute__((visibility("hidden")))
@interface SBBBWidgetBulletinInfo : SBBBBulletinInfo {
	NSString* _identifier;
	CGSize _preferredViewSize;
	BOOL _visible;
	struct {
		unsigned _didFetchDisplayName : 1;
	} _widgetBulletinInfoFlags;
}
@property(readonly, retain) NSString* identifier;
@property(assign, nonatomic) CGSize preferredViewSize;
@property(readonly, assign, nonatomic) SBWidgetViewControllerHost* representedWidget;
- (void)dealloc;
- (float)heightForReusableViewForBulletinViewController:(id)bulletinViewController layoutMode:(int)mode;
- (id)originalSectionIdentifier;
- (void)populateReusableView:(id)view;
- (id)representedBulletin;
- (Class)reusableViewClass;
- (id)widgetIdentifier;
@end

