/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBDefaultBannerViewSource.h"

@class UIImage, BBBulletin, SBUISound, NSArray, BBObserver;

__attribute__((visibility("hidden")))
@interface SBBulletinBannerItem : XXUnknownSuperclass <SBDefaultBannerViewSource> {
	BBBulletin* _seedBulletin;
	BBObserver* _observer;
	NSArray* _additionalBulletins;
	UIImage* _iconImage;
	SBUISound* _sound;
}
@property(readonly, retain) NSArray* additionalBulletins;
@property(readonly, retain) UIImage* iconImage;
@property(readonly, retain) BBBulletin* seedBulletin;
@property(readonly, retain) SBUISound* sound;
+ (id)itemWithBulletin:(id)bulletin andObserver:(id)observer;
+ (id)itemWithSeedBulletin:(id)seedBulletin additionalBulletins:(id)bulletins andObserver:(id)observer;
- (id)_appName;
- (id)_initWithSeedBulletin:(id)seedBulletin additionalBulletins:(id)bulletins andObserver:(id)observer;
- (void)_setSound;
- (unsigned)accessoryStyle;
- (id)action;
- (id)attachmentImage;
- (id)attachmentText;
- (BOOL)canShowInAssistant;
- (void)dealloc;
- (BOOL)inertWhenLocked;
- (BOOL)isCritical;
- (BOOL)isVIP;
- (id)message;
- (BOOL)overridesQuietMode;
- (id)pullDownNotification;
- (id)sortDate;
- (id)sourceDate;
- (id)title;
@end

