/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBControlCenterSectionView.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBCCButtonLayoutView : SBControlCenterSectionView {
	NSMutableArray* _buttons;
	float _interButtonPadding;
	UIEdgeInsets _contentEdgeInsets;
}
@property(readonly, retain) NSMutableArray* buttons;
@property(assign, nonatomic) UIEdgeInsets contentEdgeInsets;
@property(assign, nonatomic) float interButtonPadding;
- (id)initWithFrame:(CGRect)frame;
- (void)addButton:(id)button;
- (void)dealloc;
- (void)layoutSubviews;
- (void)removeButton:(id)button;
@end

