/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"
#import "SBUIControlCenterControl.h"


__attribute__((visibility("hidden")))
@interface SBControlCenterKnockoutView : XXUnknownSuperclass <SBUIControlCenterControl> {
}
- (id)initWithFrame:(CGRect)frame;
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;
- (void)controlAppearanceDidChangeForState:(int)controlAppearance;
- (void)controlConfigurationDidChangeForState:(int)controlConfiguration;
- (void)dealloc;
@end

