/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBDateTimeCache : XXUnknownSuperclass {
	double _yesterday;
	double _today;
	double _tomorrow;
	double _2daysFromNow;
	double _6daysAgo;
	double _prevWeek;
	double _nextWeek;
	double _lastAttemptedResetTime;
	double _lastSuccessfulResetTime;
}
@property(readonly, assign) double nextWeek;
@property(readonly, assign) double prevWeek;
@property(readonly, assign) double today;
@property(readonly, assign) double tomorrow;
@property(readonly, assign) double yesterday;
+ (id)sharedInstance;
- (id)init;
- (BOOL)_isToday:(double)today;
- (void)_resetAndConfigure;
- (void)_resetAndConfigureIfNecessary;
- (void)dealloc;
- (id)description;
- (BOOL)isToday:(double)today;
- (BOOL)isTomorrow:(double)tomorrow;
- (BOOL)isWithinNextWeek:(double)week;
- (BOOL)isWithinPrevWeek:(double)week;
- (BOOL)isWithinPrevWeek:(double)week includeToday:(BOOL)today;
- (BOOL)isYesterday:(double)yesterday;
@end

