/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBLeafIcon.h"

@class SBApplicationPlaceholder;

__attribute__((visibility("hidden")))
@interface SBDownloadingIcon : SBLeafIcon {
	BOOL _wasUninstalledByUser;
	BOOL _isNewsstandDownload;
	SBApplicationPlaceholder* _appPlaceholder;
}
@property(readonly, retain) SBApplicationPlaceholder* appPlaceholder;
@property(assign, getter=isNewsstandDownload) BOOL newsstandDownload;
@property(assign) BOOL uninstalledByUser;
+ (id)leafIdentifierForApplicationPlaceholderBundleID:(id)applicationPlaceholderBundleID;
- (id)initWithApplicationPlaceholder:(id)applicationPlaceholder;
- (id)_darkenedIconImageForImage:(id)image;
- (void)_showAlertForError:(id)error;
- (void)cancelDownload;
- (void)completeUninstall;
- (id)copyWithZone:(NSZone*)zone;
- (void)dealloc;
- (id)description;
- (id)gridCellImage;
- (id)homescreenIconImage;
- (BOOL)iconAppearsInNewsstand;
- (BOOL)isDownloadingIcon;
- (id)realDisplayName;
- (void)reloadForStatusChange;
- (void)setApplicationPlaceholder:(id)placeholder;
- (id)uninstallAlertBody;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertTitle;
@end

