/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface SBEmergencyCallView : XXUnknownSuperclass {
	UIView* _topBar;
}
@property(retain) UIView* topBar;
- (id)initWithFrame:(CGRect)frame topBarFrame:(CGRect)frame2 bottomBarFrame:(CGRect)frame3;
- (void)dealloc;
@end

