/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBFolderViewDelegate.h"
#import "SpringBoard-Structs.h"

@class SBIconViewMap, SBFolderView;

__attribute__((visibility("hidden")))
@interface SBHomeScreenPreviewView : XXUnknownSuperclass <SBFolderViewDelegate> {
	SBIconViewMap* _viewMap;
	SBFolderView* _folderContent;
}
+ (void)cleanupPreview;
+ (id)preview;
- (id)initWithFrame:(CGRect)frame iconController:(id)controller;
- (void)dealloc;
- (void)folderView:(id)view currentPageIndexDidChange:(int)currentPageIndex;
- (void)folderViewDidEndScrolling:(id)folderView;
- (void)folderViewShouldBeginEditing:(id)folderView;
- (void)folderViewShouldClose:(id)folderView;
- (void)folderViewWillBeginScrolling:(id)folderView;
- (Class)iconListViewClassForFolderView:(id)folderView;
@end

