/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBLockStateAggregator : XXUnknownSuperclass {
	unsigned _lockState;
}
@property(readonly, assign) unsigned lockState;
+ (id)sharedInstance;
- (id)init;
- (id)_descriptionForLockState:(unsigned)lockState;
- (void)_updateLockState;
- (void)dealloc;
- (id)description;
- (BOOL)hasAnyLockState;
@end

