/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBLockScreenBatteryChargingView, NSTimer;
@protocol SBLockScreenBatteryChargingViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBLockScreenBatteryChargingViewController : XXUnknownSuperclass {
	SBLockScreenBatteryChargingView* _chargingView;
	NSTimer* _visibilityTimer;
	BOOL _displayDetailedCharge;
	int _chargePercentage;
	id<SBLockScreenBatteryChargingViewControllerDelegate> _delegate;
}
@property(readonly, retain) SBLockScreenBatteryChargingView* chargingView;
@property(assign, nonatomic) id<SBLockScreenBatteryChargingViewControllerDelegate> delegate;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
- (void)_batteryStatusChanged:(id)changed;
- (void)_clearVisibilityTimer;
- (void)_visibilityTimerFired:(id)fired;
- (BOOL)batteryVisible;
- (void)dealloc;
- (void)loadView;
- (void)prepareForDismissal;
- (void)showChargeLevelWithBatteryVisible:(BOOL)batteryVisible;
@end

