/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIAlertView, UIView;

__attribute__((visibility("hidden")))
@interface SBLockScreenModalAlertView : XXUnknownSuperclass {
	UIAlertView* _alertView;
	UIView* _realModalAlertView;
}
- (id)initWithFrame:(CGRect)frame;
- (void)dealloc;
- (void)layoutSubviews;
- (void)removeAlertView;
- (void)showAlertView:(id)view;
@end

