/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBPasscodeLockAssertionTracker : XXUnknownSuperclass {
	MKBAssertionRef _mkbAssertion;
	NSMutableSet* _assertions;
}
- (id)init;
- (void)addAssertion:(id)assertion;
- (void)dealloc;
- (id)description;
- (BOOL)hasActiveAssertions;
- (id)mkbAssertionOptions;
- (void)removeAssertion:(id)assertion;
@end

