/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"
#import "SBUIPasscodeLockViewDelegate.h"


__attribute__((visibility("hidden")))
@interface SBPasscodeEntryAlertViewController : SBAlert <SBUIPasscodeLockViewDelegate> {
	BOOL _attemptingUnlock;
}
- (void)_passcodeLockViewPasscodeEntered:(id)entered viaMesa:(BOOL)mesa;
- (id)alertDisplayViewWithSize:(CGSize)size;
- (void)deactivate;
- (BOOL)hasTranslucentBackground;
- (void)passcodeLockViewCancelButtonPressed:(id)pressed;
- (void)passcodeLockViewPasscodeDidChange:(id)passcodeLockViewPasscode;
- (void)passcodeLockViewPasscodeEntered:(id)entered;
- (void)passcodeLockViewPasscodeEnteredViaMesa:(id)mesa;
@end

