/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSSet, NSDictionary, NSOrderedSet, NSLock, NSString;

__attribute__((visibility("hidden")))
@interface SBPlatformController : XXUnknownSuperclass {
	NSString* _currentConfigurationName;
	long _defaultIconInfoOnce;
	NSDictionary* _defaultStarkIconState;
	NSDictionary* _defaultIconState;
	NSOrderedSet* _defaultIconStateDisplayIdentifiers;
	NSLock* _iconStateDisplayIdentifiersLock;
	NSSet* _iconStateDisplayIdentifiers;
	NSString* _localizedDeviceName;
	BOOL _hasGasGauge;
	BOOL _supportsOpenGLES2;
	BOOL _internalInstall;
	BOOL _carrierInstall;
	BOOL _singleCoreDevice;
}
@property(readonly, assign, getter=isCarrierInstall) BOOL carrierInstall;
@property(readonly, retain) NSDictionary* defaultIconState;
@property(readonly, retain) NSOrderedSet* defaultIconStateDisplayIdentifiers;
@property(readonly, retain) NSDictionary* defaultStarkIconState;
@property(readonly, assign) BOOL hasGasGauge;
@property(readonly, retain) NSSet* iconStateDisplayIdentifiers;
@property(readonly, assign, getter=isInternalInstall) BOOL internalInstall;
@property(readonly, assign, getter=isSingleCoreDevice) BOOL singleCoreDevice;
@property(readonly, assign) BOOL supportsOpenGLES2;
+ (id)deviceClass;
+ (id)hardwareModel;
+ (id)productType;
+ (id)sharedInstance;
+ (id)systemBuildVersion;
+ (id)uniqueDeviceIdentifier;
- (id)init;
- (id)_currentConfigurationName;
- (void)_loadDefaultIconInfoIfNecessary;
- (void)_visibleIdentifiersChanged:(id)changed;
- (void)dealloc;
- (BOOL)isN90Like;
- (id)localizedPlatformName;
- (void)registerForIconVisibilityChanges;
@end

