/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class SBWallpaperEffectView, UIView, _UIBackdropView;

__attribute__((visibility("hidden")))
@interface SBSearchResultsBackdropView : XXUnknownSuperclass {
	_UIBackdropView* _backdropView;
	SBWallpaperEffectView* _effectView;
	UIView* _tintView;
}
- (id)initWithFrame:(CGRect)frame;
- (void)dealloc;
- (void)layoutSubviews;
@end

