/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@protocol SBSizeObservingViewDelegate;

__attribute__((visibility("hidden")))
@interface SBSizeObservingView : XXUnknownSuperclass {
	BOOL _delegateInterestedInSizeChanges;
	id<SBSizeObservingViewDelegate> _delegate;
}
@property(assign, nonatomic) id<SBSizeObservingViewDelegate> delegate;
- (void)setBounds:(CGRect)bounds;
- (void)setFrame:(CGRect)frame;
@end

