/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBTestRecipe.h"

@class SBTestStarkAlert;

__attribute__((visibility("hidden")))
@interface SBStarkAlertRecipe : XXUnknownSuperclass <SBTestRecipe> {
	SBTestStarkAlert* _alert;
}
+ (id)title;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
@end

