/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSFastEnumeration.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBStringMetrics : XXUnknownSuperclass <NSFastEnumeration> {
	NSMutableArray* _fragments;
}
@property(readonly, retain) NSMutableArray* fragments;
- (id)init;
- (void)addFragment:(id)fragment;
- (unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
- (void)dealloc;
- (id)description;
- (unsigned)fragmentCount;
@end

