/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBCollectionViewCell.h"
#import "SBUIBannerView.h"
#import "SpringBoard-Structs.h"

@class UIView, SBBannerContextView;

__attribute__((visibility("hidden")))
@interface SBStarkBannerCell : SBCollectionViewCell <SBUIBannerView> {
	SBBannerContextView* _contextView;
	UIView* _darkeningOverlayView;
}
@property(retain) id bannerContext;
- (id)initWithFrame:(CGRect)frame;
- (void)dealloc;
- (void)noteDidAppear;
- (void)noteDidDismiss;
- (void)noteWillAppear;
- (void)noteWillDismissWithReason:(int)note;
- (void)prepareForReuse;
@end

