/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBWindowContextManagerDelegate.h"
#import "SBWindowContextHostManagerDelegate.h"
#import "SBWindow.h"

@class SBWindowContextHostManager, SBWindowContextManager;

__attribute__((visibility("hidden")))
@interface SBStarkNowPlayingWindow : SBWindow <SBWindowContextManagerDelegate, SBWindowContextHostManagerDelegate> {
	SBWindowContextManager* _contextManager;
	SBWindowContextHostManager* _contextHostManager;
}
@property(readonly, retain) SBWindowContextHostManager* contextHostManager;
- (id)initWithScreen:(id)screen jailBehavior:(int)behavior;
- (void)dealloc;
- (void)windowContextManager:(id)manager didStopTrackingContextsForScreen:(id)screen;
- (BOOL)windowContextManager:(id)manager shouldAddContext:(id)context;
- (void)windowContextManager:(id)manager willStartTrackingContextsForScreen:(id)screen;
@end

