/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertViewAdapter.h"


__attribute__((visibility("hidden")))
@interface SBUIFullscreenAlertViewAdapter : SBAlertViewAdapter {
	BOOL _revealedContentBeneathForDismiss;
	BOOL _animatingOut;
}
@property(retain) id alert;
@property(readonly, assign, getter=isAnimatingOut) BOOL animatingOut;
- (void)alertDisplayWillBecomeVisible;
- (void)dismiss;
- (BOOL)isReadyToBeRemovedFromView;
- (void)setShouldAnimateIn:(BOOL)animateIn;
- (BOOL)shouldAnimateIconsIn;
- (void)updateSpringBoardInPreparationForTransparentDismiss;
- (void)viewAnimatedOut;
@end

