/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBVoiceControlAlert : SBAlert {
	struct {
		unsigned shouldBeActivated : 1;
		unsigned isReadyToBeActivated : 1;
		unsigned hasBeenActivated : 1;
	} _voiceControlFlags;
	BOOL _expectsFaceContact;
	BOOL _expectsFaceContactInLandscape;
}
@property(assign) BOOL expectsFaceContact;
@property(readonly, assign) BOOL expectsFaceContactInLandscape;
+ (BOOL)_bluetoothDevicesPickable;
+ (void)_configureSession:(id)session forAlert:(id)alert;
+ (void)_setNextRecognitionAudioInputPathForSession:(id)session resetting:(BOOL)resetting;
+ (void)bluetoothDeviceRequestedVoiceControl:(id)control;
+ (void)bluetoothDeviceTerminatedVoiceControl:(id)control;
+ (id)pendingOrActiveAlert;
+ (void)registerForAlerts;
+ (BOOL)resetVoiceControlIfNecessary:(BOOL)necessary;
+ (void)setNextRecognitionAudioInputPaths:(id)paths;
+ (BOOL)shouldEnterVoiceControl;
+ (void)unregisterForAlerts;
- (id)init;
- (id)initFromBluetoothDevice:(id)bluetoothDevice;
- (id)initFromMenuButton;
- (id)initFromWiredHeadsetButton;
- (void)_makeActive;
- (void)_prime;
- (void)_proximityChanged:(id)changed;
- (void)_resign;
- (id)_session;
- (void)_setRoutingAttributesForWiredHeadset:(BOOL)wiredHeadset;
- (void)_workspaceActivate;
- (void)activate;
- (void)activateWhenReady;
- (id)alertDisplayViewWithSize:(CGSize)size;
- (BOOL)allowsEventOnlySuspension;
- (double)autoDimTime;
- (void)cancel;
- (void)cancelIfNotActivated;
- (void)deactivate;
- (void)dealloc;
- (void)handleHeadsetButtonUpFromActivation:(BOOL)activation;
- (BOOL)handleMenuButtonTap;
- (BOOL)recognitionSessionWillBeginAction:(id)recognitionSession;
- (void)setExpectsFaceContact:(BOOL)contact inLandscape:(BOOL)landscape;
@end

